name: Docker Image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build -t cicd-Pipeline .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:latest


        

      
      -
