name: CI-CD Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline .
      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > pipeline.pem
          chmod 600 pipeline.pem
             
      - name: Run Command on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i pipeline.pem ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
          echo "Running commands on EC2 instance"
          sudo docker stop $(docker ps)
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:latest
          sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:latest
