name: 

on:

jobs:
  job name:
    runs-on:

    steps:
      Cache NPM dependencies:
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: '${{ runner.os }}-node-modules-${{ hashFiles("package-lock.json)"}}'
